apiVersion: apps/v1
kind: Deployment
metadata:
  name: tooling-deployment
  labels:
    app: tooling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tooling
  template:
    metadata:
      labels:
        app: tooling
    spec:
      containers:
        - name: tooling
          image: citatech/tooling-app
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: DB_HOST
              value: "tooling-aurora-cluster.cluster-c3a0ywg2a6ua.us-west-1.rds.amazonaws.com"  
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "your-database-name"        
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: aurora-db-credentials    
                  key: DB_USERNAME              
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aurora-db-credentials
                  key: DB_PASSWORD  